artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "Ro551/WikiCorrupted_spanish_to_GEC-GED" #"Ro551/WikiCorrupted_spanish_to_GEC-GED_xs"
  source_cowsl2h: "Ro551/COWSL2H_GEC_cleaned"
  dataset_cache_dir: artifacts/data_ingestion/hf_dataset
  dataset_test_cache_dir: artifacts/data_ingestion/hf_dataset_test
  mode: "synthetic"

data_transformation:
  root_dir: artifacts/data_transformation
  tokenizer_name: "google/mt5-small" #"Helsinki-NLP/opus-mt-es-en"  #"facebook/m2m100_418M" #
  model_id: "mT5-Small" #"marianMT" #"facebook/m2m100_418M" #"Helsinki-NLP/opus-mt-es-en"
  save_to_disk: true  
  max_input_length: 128
  max_target_length: 128

model_trainer:
  root_dir: artifacts/model_trainer
  model_ckpt: "google/mt5-small" #"Helsinki-NLP/opus-mt-es-en" 
  run_name: "dsSint"
  project_name: "GEC-Spanish-trainer"
  num_train_epochs: 4
  lr: 0.0003140978 #0.00015888 #0.000028126
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 12
  generation_max_length: 128
  weight_decay: 0.03839904 #0.0977850 #0.0383990 #0.070
  optim: "adamw_torch"
  fp16: false
  load_best_model: true
  push_to_hub: true
  use_lora: false
  lora_config:
    r: 8
    lora_alpha: 32
    lora_dropout: 0.05
    bias: "none"

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainer
  tokenizer_path: artifacts/model_trainer
  source_file: "source.txt"
  gold_file: "gold.txt"
  pred_file: "pred.txt"
  metric_file_name: "metrics.json"

hyperparameter_tuning:
  root_dir: artifacts/hiperparameter_tuning
  source_data_URL: "Ro551/WikiCorrupted_spanish_to_GEC-GED_mini" 
  models_ckpt: ["facebook/m2m100_418M"] # ["Helsinki-NLP/opus-mt-es-en", "google/mt5-small", "facebook/m2m100_418M"]#, "facebook/mbart-large-50"]
  project_name: "Hypertuning_GEC"
  run_name: "dataSint"
  epochs: 3
  n_trials: 4
  lr: [0.0000464, 0.0001]
  wd: [0.01, 0.1]
  bs: [1, 2]
  gradient_accumulation_steps: [4, 16]
  use_lora: false
  lora_config:
    r: [4, 8, 16]
    lora_alpha: [4, 8, 16, 32, 64]
    lora_dropout: [0.05, 0.15]
    bias: "none"
