artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "Ro551/WikiCorrupted-spanish_to_GEC-GED" #"Ro551/WikiCorrupted_spanish_to_GEC-GED_med" #"Ro551/WikiCorrupted-spanish_to_GEC-GED" #
  source_cowsl2h: "Ro551/COWSL2H_GEC_cleaned"
  dataset_cache_dir: artifacts/data_ingestion/hf_dataset
  dataset_test_cache_dir: artifacts/data_ingestion/hf_dataset_test
  mode: "synthetic" #puede ser "synthetic", "cowsl2h", "merged"

data_transformation:
  root_dir: artifacts/data_transformation
  tokenizer_name: "google/mt5-large" #"Helsinki-NLP/opus-mt-es-en" #"facebook/mbart-large-50" ##"Helsinki-NLP/opus-mt-es-en"  #"facebook/m2m100_418M" #google/mt5-large google/mt5-small
  model_id: "mt5-large" #"m2m100" #"mBart" # #"marianMT, mt5-small, mt5-large" 
  save_to_disk: true  
  max_input_length: 128
  max_target_length: 128

model_trainer:
  root_dir: artifacts/model_trainer
  model_ckpt: "google/mt5-large" 
  run_name: "synthetic" #"merged" #"synthetic" cowsl2h
  re_train: false
  project_name: "Trainer-GEC_LoRA" #_exps" #"Trainer-GEC_LoRA" # "Trainer-GEC_FT"
  num_train_epochs: 2
  lr: 0.0004542233703472283
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  generation_max_length: 128
  weight_decay: 0.0792019347166952
  warmup_ratio: 0.07566828197066039
  optim: "adamw_torch" #"adafactor" #->m2m100  # "adamw_torch" #
  fp16: false
  load_best_model: true
  push_to_hub: true
  use_lora: true
  lora_config: 
    r: 32
    lora_alpha: 16
    lora_dropout: 0.15
    bias: "none"

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainer
  tokenizer_path: artifacts/model_trainer
  source_file: "source.txt"
  gold_file: "gold.txt"
  pred_file: "pred.txt"
  metric_file_name: "metrics.json"

hyperparameter_tuning:
  root_dir: artifacts/hyperparameter_tuning
  source_synthetic: "Ro551/WikiCorrupted_spanish_to_GEC-GED_mini"
  source_cowsl2h: "Ro551/COWSL2H_GEC_cleaned" 
  mode: "hybrid" # puede ser "synthetic", "cowsl2h", "hybrid"
  models_ckpt: ["facebook/m2m100_418M"] #, "Helsinki-NLP/opus-mt-es-en", "facebook/m2m100_418M"] #"facebook/mbart-large-50"] #google/mt5-small",
  project_name: "Hypertuning_GEC_FT" #"Hypertuning_GEC_LoRA"  
  epochs: 3
  n_trials: 2
  lr: [0.00001, 0.0006]  # mt5large-smal:[0.00005, 0.001] #[0.000005, 0.0002] #->lora  ft:[0.00001, 0.0006] 
  wd: [0.00, 0.1]
  wr: [0.05, 0.1]
  use_lora: false
  lora_config:
    r: [16, 32, 64]
    lora_alpha: 16
    lora_dropout: [0.05, 0.15]
    bias: "none"
